/**
 * AI 员工窗口所连接后端（async-agent-proxy）广播的 WebSocket 事件名字符串。
 * 与代理侧协议常量逐字一致；用于契约测试与校验。
 */
export const AI_EMPLOYEES_WS_EVENT_NAMES = [
	'issue:created',
	'issue:updated',
	'issue:deleted',
	'comment:created',
	'comment:updated',
	'comment:deleted',
	'reaction:added',
	'reaction:removed',
	'issue_reaction:added',
	'issue_reaction:removed',
	'agent:status',
	'agent:created',
	'agent:archived',
	'agent:restored',
	'task:dispatch',
	'task:progress',
	'task:completed',
	'task:failed',
	'task:message',
	'task:cancelled',
	'task:approval-requested',
	'task:approved',
	'task:rejected',
	'inbox:new',
	'inbox:read',
	'inbox:archived',
	'inbox:batch-read',
	'inbox:batch-archived',
	'workspace:updated',
	'workspace:deleted',
	'member:added',
	'member:updated',
	'member:removed',
	'subscriber:added',
	'subscriber:removed',
	'activity:created',
	'skill:created',
	'skill:updated',
	'skill:deleted',
	'chat:message',
	'chat:done',
	'project:created',
	'project:updated',
	'project:deleted',
	'daemon:heartbeat',
	'daemon:register',
] as const;

export type AiEmployeesWsEventName = (typeof AI_EMPLOYEES_WS_EVENT_NAMES)[number];
